/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer_table_Jframes;

/**
 *
 * @author koralekankanamgenilanthajanaka
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addCusForm = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        quickModeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CUSTOMER PAGE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 17, -1, -1));

        addCusForm.setBackground(new java.awt.Color(255, 153, 0));
        addCusForm.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        addCusForm.setText("ADD CUSTOMER");
        addCusForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusFormActionPerformed(evt);
            }
        });
        jPanel3.add(addCusForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 50));

        updateBtn.setBackground(new java.awt.Color(255, 153, 0));
        updateBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        updateBtn.setText("UPDATE CUSTOMER");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel3.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 50));

        searchBtn.setBackground(new java.awt.Color(255, 153, 0));
        searchBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        searchBtn.setText("SEARCH CUSTOMER");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 50));

        deleteBtn.setBackground(new java.awt.Color(255, 153, 0));
        deleteBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        deleteBtn.setText("DELETE CUSTOMER");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 50));

        viewBtn.setBackground(new java.awt.Color(255, 153, 0));
        viewBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        viewBtn.setText("VIEW CUSTOMER");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, 50));

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("@RAKITHA_AMADITHYA");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 153, 0));
        exitBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        exitBtn.setText("CANCEL");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, 40));

        quickModeBtn.setBackground(new java.awt.Color(204, 0, 51));
        quickModeBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        quickModeBtn.setText("QUICK MODE");
        quickModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickModeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(quickModeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 50));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("GOOD ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 25, 139, -1));

        jLabel5.setFont(new java.awt.Font("Myanmar MN", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("STORE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 26, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFramePackage/images/customer.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 460, 470));

        setSize(new java.awt.Dimension(727, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
         view_customer_form view = new view_customer_form ();  
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewBtnActionPerformed

    private void addCusFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusFormActionPerformed
        add_customer_form acf = new add_customer_form ();  
        acf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCusFormActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        main_frame hPge = new main_frame ();  
        hPge.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         update_customer_form update = new update_customer_form ();  
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        search_customer_form search = new search_customer_form ();  
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        delete_customer_form delete = new delete_customer_form ();  
        delete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void quickModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickModeBtnActionPerformed
        Quick_Access_Customer QAC = new Quick_Access_Customer ();  
        QAC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quickModeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new customer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCusForm;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton quickModeBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
