/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Customer_table_Jframes.Quick_Access_Customer;
import Customer_table_Jframes.main_frame;
import controller.CustomerController;
import controller.OrderController;
import database.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.OrderDetail;
import model.Orders;

/**
 *
 * @author koralekankanamgenilanthajanaka
 */
public class thogaKade_pos extends javax.swing.JFrame {

    /**
     * Creates new form thogaKade_pos
     */
    public thogaKade_pos() {
        initComponents();
        loadDate();
        try {
            setOrderId();
            setItemCode();
        } catch (SQLException ex) {
            Logger.getLogger(thogaKade_pos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(thogaKade_pos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        orderDateBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ORDIDBOX = new javax.swing.JTextField();
        cmbItemCode = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusId = new javax.swing.JTextField();
        addCusForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        totalBox = new javax.swing.JTextField();
        subTotBox = new javax.swing.JTextField();
        taxBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        keerisambaBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        redRawRice = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        whiteRice = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        DHAL = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        greenGram = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        chickPeas = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        cannedFish = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        OIL = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        ANCHOR = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        SUGAR = new javax.swing.JButton();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        ASTRA = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        FLOUR = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        PASTA = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        SAUCE = new javax.swing.JButton();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        CHEESE = new javax.swing.JButton();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        BREAD = new javax.swing.JButton();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        YOGHURT = new javax.swing.JButton();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        COCACOLA = new javax.swing.JButton();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        FACEWASH = new javax.swing.JButton();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        TOOTHPASTE = new javax.swing.JButton();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        REMOVEBTN = new javax.swing.JButton();
        RESETBTN = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        placeOrderBtn = new javax.swing.JButton();
        mainpg = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText(" DATE   ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        orderDateBox.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        orderDateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDateBoxActionPerformed(evt);
            }
        });
        jPanel1.add(orderDateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, 40));

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("ORD ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ORDIDBOX.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        ORDIDBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDIDBOXActionPerformed(evt);
            }
        });
        jPanel1.add(ORDIDBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 40));

        cmbItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemCodeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 160));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("NAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 80, 40));

        cusName.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        cusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusNameActionPerformed(evt);
            }
        });
        jPanel2.add(cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, 50));

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("CUS ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, 40));

        cusId.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        cusId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusIdActionPerformed(evt);
            }
        });
        jPanel2.add(cusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, 50));

        addCusForm.setBackground(new java.awt.Color(102, 204, 0));
        addCusForm.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        addCusForm.setText("NEW");
        addCusForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusFormActionPerformed(evt);
            }
        });
        jPanel2.add(addCusForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 170, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 320, 210));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "DESCRIPTION", "QTY", "UNIT PRICE", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 680, 530));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalBox.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jPanel3.add(totalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, 40));

        subTotBox.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jPanel3.add(subTotBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 40));

        taxBox.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jPanel3.add(taxBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 40));

        jLabel11.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel11.setText("SUB TOT");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jLabel12.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel12.setText("TAX");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel13.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("TOTAL");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 320, 160));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keerisambaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/KEERI SAMBA RICE.jpg"))); // NOI18N
        keerisambaBtn.setText("jButton4");
        keerisambaBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        keerisambaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keerisambaBtnActionPerformed(evt);
            }
        });
        jPanel4.add(keerisambaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 180));

        jTextField1.setBackground(new java.awt.Color(255, 153, 0));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Rs.299/=");
        jTextField1.setEditable(false);
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 40));

        jTextField2.setBackground(new java.awt.Color(255, 153, 0));
        jTextField2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("KEERI SAMBA RETAIL");
        jTextField2.setEditable(false);
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        redRawRice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/RR.jpg"))); // NOI18N
        redRawRice.setText("jButton4");
        redRawRice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        redRawRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redRawRiceActionPerformed(evt);
            }
        });
        jPanel4.add(redRawRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, 180));

        jTextField3.setBackground(new java.awt.Color(255, 153, 0));
        jTextField3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("RED RAW RICE RETAIL");
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, 40));

        jTextField4.setBackground(new java.awt.Color(255, 153, 0));
        jTextField4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Rs.172.5/=");
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, 40));

        whiteRice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/whiteRice.jpg"))); // NOI18N
        whiteRice.setText("jButton4");
        whiteRice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        whiteRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteRiceActionPerformed(evt);
            }
        });
        jPanel4.add(whiteRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 180, 180));

        jTextField5.setBackground(new java.awt.Color(255, 153, 0));
        jTextField5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("WHITE RICE RETAIL");
        jTextField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 180, 40));

        jTextField6.setBackground(new java.awt.Color(255, 153, 0));
        jTextField6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Rs184/=");
        jTextField6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, 40));

        DHAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/DHAL.jpg"))); // NOI18N
        DHAL.setText("jButton4");
        DHAL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DHAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DHALActionPerformed(evt);
            }
        });
        jPanel4.add(DHAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 180, 180));

        jTextField7.setBackground(new java.awt.Color(255, 153, 0));
        jTextField7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("RED DHAL RETAIL");
        jTextField7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 180, 40));

        jTextField8.setBackground(new java.awt.Color(255, 153, 0));
        jTextField8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Rs.402.5/=");
        jTextField8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 180, 40));

        greenGram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/GREEN GRAM.jpg"))); // NOI18N
        greenGram.setText("jButton4");
        greenGram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        greenGram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenGramActionPerformed(evt);
            }
        });
        jPanel4.add(greenGram, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 180));

        jTextField9.setBackground(new java.awt.Color(255, 153, 0));
        jTextField9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("GREEN GRAM");
        jTextField9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 180, 40));

        jTextField10.setBackground(new java.awt.Color(255, 153, 0));
        jTextField10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Rs.1092.5/=");
        jTextField10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, 40));

        chickPeas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/KADALA.jpg"))); // NOI18N
        chickPeas.setText("jButton4");
        chickPeas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chickPeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickPeasActionPerformed(evt);
            }
        });
        jPanel4.add(chickPeas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, 180));

        jTextField11.setBackground(new java.awt.Color(255, 153, 0));
        jTextField11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("CHICK PEAS");
        jTextField11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 180, 40));

        jTextField12.setBackground(new java.awt.Color(255, 153, 0));
        jTextField12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs747.5/=");
        jTextField12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 180, 40));

        cannedFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SAMEN.jpg"))); // NOI18N
        cannedFish.setText("jButton4");
        cannedFish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cannedFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cannedFishActionPerformed(evt);
            }
        });
        jPanel4.add(cannedFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 180, 180));

        jTextField13.setBackground(new java.awt.Color(255, 153, 0));
        jTextField13.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("CANNED FISH");
        jTextField13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 180, 40));

        jTextField14.setBackground(new java.awt.Color(255, 153, 0));
        jTextField14.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Rs.402.5/=");
        jTextField14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 180, 40));

        OIL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/oil.jpg"))); // NOI18N
        OIL.setText("jButton4");
        OIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OILActionPerformed(evt);
            }
        });
        jPanel4.add(OIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 180, 180));

        jTextField15.setBackground(new java.awt.Color(255, 153, 0));
        jTextField15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("PREMA VEG OIL");
        jTextField15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 180, 40));

        jTextField16.setBackground(new java.awt.Color(255, 153, 0));
        jTextField16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("Rs.1115.5/=");
        jTextField16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, 40));

        ANCHOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/MILK PACKET.jpg"))); // NOI18N
        ANCHOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ANCHOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANCHORActionPerformed(evt);
            }
        });
        jPanel4.add(ANCHOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 180, 180));

        jTextField17.setBackground(new java.awt.Color(255, 153, 0));
        jTextField17.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("ANCHOR MILK 1KG");
        jTextField17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 180, 40));

        jTextField18.setBackground(new java.awt.Color(255, 153, 0));
        jTextField18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("Rs.2461/=");
        jTextField18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 180, 40));

        SUGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SUGAR.jpg"))); // NOI18N
        SUGAR.setText("jButton4");
        SUGAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SUGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUGARActionPerformed(evt);
            }
        });
        jPanel4.add(SUGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 180, 180));

        jTextField19.setBackground(new java.awt.Color(255, 153, 0));
        jTextField19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("SUGAR 1KG");
        jTextField19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, 180, 40));

        jTextField20.setBackground(new java.awt.Color(255, 153, 0));
        jTextField20.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("Rs.402.5/=");
        jTextField20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, 180, 40));

        ASTRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ASTRA.jpg"))); // NOI18N
        ASTRA.setText("jButton4");
        ASTRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ASTRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASTRAActionPerformed(evt);
            }
        });
        jPanel4.add(ASTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 180, 180));

        jTextField21.setBackground(new java.awt.Color(255, 153, 0));
        jTextField21.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("ASTRA MAGARIN 100g");
        jTextField21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 740, 180, 40));

        jTextField22.setBackground(new java.awt.Color(255, 153, 0));
        jTextField22.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("Rs.299/=");
        jTextField22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 180, 40));

        FLOUR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/FLOUR.jpg"))); // NOI18N
        FLOUR.setText("jButton4");
        FLOUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FLOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FLOURActionPerformed(evt);
            }
        });
        jPanel4.add(FLOUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 180, 180));

        jTextField23.setBackground(new java.awt.Color(255, 153, 0));
        jTextField23.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("WHEAT FLOUR");
        jTextField23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 740, 180, 40));

        jTextField24.setBackground(new java.awt.Color(255, 153, 0));
        jTextField24.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("Rs333.5/=");
        jTextField24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 780, 180, 40));

        PASTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/PASTA.jpg"))); // NOI18N
        PASTA.setText("jButton4");
        PASTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PASTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASTAActionPerformed(evt);
            }
        });
        jPanel4.add(PASTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, 180, 180));

        jTextField25.setBackground(new java.awt.Color(255, 153, 0));
        jTextField25.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("SUBWAY PASTA 1KG");
        jTextField25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1010, 180, 40));

        jTextField26.setBackground(new java.awt.Color(255, 153, 0));
        jTextField26.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("Rs.1138.5/=");
        jTextField26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1050, 180, 40));

        SAUCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TOMATO SAUSE.jpg"))); // NOI18N
        SAUCE.setText("jButton4");
        SAUCE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SAUCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAUCEActionPerformed(evt);
            }
        });
        jPanel4.add(SAUCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, 180, 180));

        jTextField27.setBackground(new java.awt.Color(255, 153, 0));
        jTextField27.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("HEINZ TOMATO SAUCE");
        jTextField27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1010, 180, 40));

        jTextField28.setBackground(new java.awt.Color(255, 153, 0));
        jTextField28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setText("Rs.897/=");
        jTextField28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1050, 180, 40));

        CHEESE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/CHEAS.jpg"))); // NOI18N
        CHEESE.setText("jButton4");
        CHEESE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CHEESE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHEESEActionPerformed(evt);
            }
        });
        jPanel4.add(CHEESE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 830, 180, 180));

        jTextField29.setBackground(new java.awt.Color(255, 153, 0));
        jTextField29.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setText("KRAFT_CHEESE 200G");
        jTextField29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1010, 180, 40));

        jTextField30.setBackground(new java.awt.Color(255, 153, 0));
        jTextField30.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText("Rs.782/=");
        jTextField30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1050, 180, 40));

        BREAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ARNOLD BREAD.jpg"))); // NOI18N
        BREAD.setText("jButton4");
        BREAD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BREAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BREADActionPerformed(evt);
            }
        });
        jPanel4.add(BREAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 830, 180, 180));

        jTextField31.setBackground(new java.awt.Color(255, 153, 0));
        jTextField31.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setText("WHITE BREAD");
        jTextField31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1010, 180, 40));

        jTextField32.setBackground(new java.awt.Color(255, 153, 0));
        jTextField32.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText("Rs184/=");
        jTextField32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1050, 180, 40));

        YOGHURT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Kotmale-Set-Yoghurt-80g.jpg"))); // NOI18N
        YOGHURT.setText("jButton4");
        YOGHURT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        YOGHURT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YOGHURTActionPerformed(evt);
            }
        });
        jPanel4.add(YOGHURT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1100, 180, 180));

        jTextField33.setBackground(new java.awt.Color(255, 153, 0));
        jTextField33.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("KOTHMALE YOGHURT");
        jTextField33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1280, 180, 40));

        jTextField34.setBackground(new java.awt.Color(255, 153, 0));
        jTextField34.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("Rs.69/=");
        jTextField34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1320, 180, 40));

        COCACOLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/COCACOLA.jpg"))); // NOI18N
        COCACOLA.setText("jButton4");
        COCACOLA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        COCACOLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COCACOLAActionPerformed(evt);
            }
        });
        jPanel4.add(COCACOLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1100, 180, 180));

        jTextField35.setBackground(new java.awt.Color(255, 153, 0));
        jTextField35.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText("COCA-COLA 500ML");
        jTextField35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1280, 180, 40));

        jTextField36.setBackground(new java.awt.Color(255, 153, 0));
        jTextField36.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setText("Rs.276/=");
        jTextField36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1320, 180, 40));

        FACEWASH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/18043-4rever-Seaweed-Nourishing-Face-Wash.jpg"))); // NOI18N
        FACEWASH.setText("jButton4");
        FACEWASH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FACEWASH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACEWASHActionPerformed(evt);
            }
        });
        jPanel4.add(FACEWASH, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1100, 180, 180));

        jTextField37.setBackground(new java.awt.Color(255, 153, 0));
        jTextField37.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setText("4EVER 150ML");
        jTextField37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1280, 180, 40));

        jTextField38.setBackground(new java.awt.Color(255, 153, 0));
        jTextField38.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("Rs.310.5/=");
        jTextField38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1320, 180, 40));

        TOOTHPASTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TOOTHPAST.jpg"))); // NOI18N
        TOOTHPASTE.setText("jButton4");
        TOOTHPASTE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TOOTHPASTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOOTHPASTEActionPerformed(evt);
            }
        });
        jPanel4.add(TOOTHPASTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1100, 180, 180));

        jTextField39.setBackground(new java.awt.Color(255, 153, 0));
        jTextField39.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("CLOSEUP 100g");
        jTextField39.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1280, 180, 40));

        jTextField40.setBackground(new java.awt.Color(255, 153, 0));
        jTextField40.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setText("Rs345/=");
        jTextField40.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1320, 180, 40));

        jScrollPane2.setViewportView(jPanel4);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 800, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 102, 153));
        jLabel8.setFont(new java.awt.Font("Malayalam MN", 1, 98)); // NOI18N
        jLabel8.setText("POS SYSTEM");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, -10, 660, 140));

        jLabel9.setBackground(new java.awt.Color(0, 102, 153));
        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 98)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("GOOD ");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 400, -1));

        jLabel10.setFont(new java.awt.Font("Myanmar MN", 1, 98)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("STORE");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, 130));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 110));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        REMOVEBTN.setBackground(new java.awt.Color(255, 51, 51));
        REMOVEBTN.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        REMOVEBTN.setText("REMOVE");
        REMOVEBTN.setBorder(new javax.swing.border.MatteBorder(null));
        REMOVEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEBTNActionPerformed(evt);
            }
        });
        jPanel6.add(REMOVEBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 230, 80));

        RESETBTN.setBackground(new java.awt.Color(255, 51, 51));
        RESETBTN.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        RESETBTN.setText("RESET");
        RESETBTN.setBorder(new javax.swing.border.MatteBorder(null));
        RESETBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETBTNActionPerformed(evt);
            }
        });
        jPanel6.add(RESETBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 240, 80));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 680, 170));

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placeOrderBtn.setBackground(new java.awt.Color(255, 153, 0));
        placeOrderBtn.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        placeOrderBtn.setText("PLACE ORDER");
        placeOrderBtn.setBorder(new javax.swing.border.MatteBorder(null));
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });
        jPanel7.add(placeOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 60));

        mainpg.setBackground(new java.awt.Color(255, 153, 51));
        mainpg.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        mainpg.setText("CANCEL");
        mainpg.setBorder(new javax.swing.border.MatteBorder(null));
        mainpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainpgActionPerformed(evt);
            }
        });
        jPanel7.add(mainpg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 60));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 320, 170));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel1.setText("@RAKITHA AMADITHYA");
        jPanel8.add(jLabel1);

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 1800, 30));

        setSize(new java.awt.Dimension(1500, 860));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setItemCode() throws SQLException, ClassNotFoundException{
          ResultSet rst = DBConnection.getInstance().getConnection().prepareStatement("SELECT * FROM Item").executeQuery();
          ArrayList<String> codes=new ArrayList<>();
          while(rst.next()){
               codes.add(rst.getString(1));
          }
          for(String x : codes){
          cmbItemCode.addItem(x);
          }
    }
    
        private void setOrderId() {
        try {
            String lastOrderId = OrderController.getLastOrderId();
            if (lastOrderId != null) {
                lastOrderId = lastOrderId.split("[A-Z]")[1]; // D001==> 001
                System.out.println(lastOrderId);
                lastOrderId = String.format("D%03d", (Integer.parseInt(lastOrderId) + 1));
                ORDIDBOX.setText(lastOrderId);
            } else {
                ORDIDBOX.setText("D001");
            }
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    private void cusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusNameActionPerformed

    private void cusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusIdActionPerformed
        try {
            Customer customer = CustomerController.searchCustomer(cusId.getText());
            if (customer != null) {
                cusName.setText(customer.getName());

            } else {
                JOptionPane.showMessageDialog(this, "Customer not found..");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_cusIdActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void orderDateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderDateBoxActionPerformed

    private void keerisambaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keerisambaBtnActionPerformed
        double priceOfItem = 260;
        //double tax = 39;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO1") && model.getValueAt(i, 1).equals("KEERI SAMBA RETAIL")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO1", "KEERI SAMBA RETAIL", 1, priceOfItem, priceOfItem });
        }
        itemCost();
    }//GEN-LAST:event_keerisambaBtnActionPerformed

    private void redRawRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redRawRiceActionPerformed
        double priceOfItem = 150;
        double tax = 22.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO2") && model.getValueAt(i, 1).equals("RED RAW RICE RETAIL")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO2", "RED RAW RICE RETAIL", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_redRawRiceActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void whiteRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteRiceActionPerformed
        double priceOfItem = 160;
        double tax = 24;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO3") && model.getValueAt(i, 1).equals("WHITE RICE RETAIL")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO3", "WHITE RICE RETAIL", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_whiteRiceActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void DHALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DHALActionPerformed
        double priceOfItem = 350;
        double tax = 52.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO4") && model.getValueAt(i, 1).equals("RED DHAL RETAIL")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO4", "RED DHAL RETAIL", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_DHALActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void greenGramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenGramActionPerformed
        double priceOfItem = 950;
        double tax = 142.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO5") && model.getValueAt(i, 1).equals("GREEN GRAM")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO5", "GREEN GRAM", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_greenGramActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void chickPeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickPeasActionPerformed
        double priceOfItem = 650;
        double tax = 97.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO6") && model.getValueAt(i, 1).equals("CHICK PEAS")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO6", "CHICK PEAS", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_chickPeasActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void cannedFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cannedFishActionPerformed
        double priceOfItem = 350;
        double tax = 52.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO7") && model.getValueAt(i, 1).equals("CANNED FISH")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO7", "CANNED FISH", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_cannedFishActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void OILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OILActionPerformed
        double priceOfItem = 970;
        double tax = 145.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO8") && model.getValueAt(i, 1).equals("PREMA VEG OIL")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO8", "PREMA VEG OIL", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_OILActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void ANCHORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANCHORActionPerformed
        double priceOfItem = 2140;
        double tax = 321;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("POO9") && model.getValueAt(i, 1).equals("ANCHOR MILK 1KG")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"POO9", "ANCHOR MILK 1KG", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_ANCHORActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void SUGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUGARActionPerformed
        double priceOfItem = 350;
        double tax = 52.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO10") && model.getValueAt(i, 1).equals("SUGAR 1KG")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO10", "SUGAR 1KG", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_SUGARActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void ASTRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASTRAActionPerformed
        double priceOfItem = 260;
        double tax = 39;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO11") && model.getValueAt(i, 1).equals("ASTRA MAGARIN 100g")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO11", "ASTRA MAGARIN 100g", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_ASTRAActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void FLOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLOURActionPerformed
        double priceOfItem = 290;
        double tax = 43.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO12") && model.getValueAt(i, 1).equals("WHEAT FLOUR")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO12", "WHEAT FLOUR", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_FLOURActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void PASTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASTAActionPerformed
        double priceOfItem = 990;
        double tax = 148.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO13") && model.getValueAt(i, 1).equals("PASTA")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO13", "PASTA", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_PASTAActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void SAUCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAUCEActionPerformed
        double priceOfItem = 780;
        double tax = 117;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO14") && model.getValueAt(i, 1).equals("HEINZ TOMATO SAUCE")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO14", "HEINZ TOMATO SAUCE", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_SAUCEActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void CHEESEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHEESEActionPerformed
        double priceOfItem = 680;
        double tax = 102;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO15") && model.getValueAt(i, 1).equals("KRAFT_CHEESE 200G")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO15", "KRAFT_CHEESE 200G", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_CHEESEActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void BREADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BREADActionPerformed
        double priceOfItem = 160;
        double tax = 24;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO16") && model.getValueAt(i, 1).equals("WHITE BREAD")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO16", "WHITE BREAD", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_BREADActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void YOGHURTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YOGHURTActionPerformed
        double priceOfItem = 60;
        double tax = 29;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO17") && model.getValueAt(i, 1).equals("KOTHMALE YOGHURT")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO17", "KOTHMALE YOGHURT", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_YOGHURTActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void COCACOLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COCACOLAActionPerformed
        double priceOfItem = 240;
        double tax = 36;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO18") && model.getValueAt(i, 1).equals("COCA-COLA 500ML")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO18", "COCA-COLA 500ML", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_COCACOLAActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void FACEWASHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACEWASHActionPerformed
        double priceOfItem = 270;
        double tax = 40.5;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO19") && model.getValueAt(i, 1).equals("4EVER 150ML")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO19", "4EVER 150ML", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_FACEWASHActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed

    }//GEN-LAST:event_jTextField38ActionPerformed

    private void TOOTHPASTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOOTHPASTEActionPerformed
        double priceOfItem = 300;
        double tax = 45;
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        int rowCount = model.getRowCount();
        boolean itemExists = false;
        int existingRow = -1;
        for (int i = 0; i < rowCount; i++) {
            if (model.getValueAt(i, 0).equals("PO20") && model.getValueAt(i, 1).equals("CLOSEUP 100g")) {
                itemExists = true;
                existingRow = i;
                break;
            }
        }

        if (itemExists) {
            int currentQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());

            model.setValueAt(currentQty + 1, existingRow, 2);
            model.setValueAt((currentQty + 1) * priceOfItem, existingRow, 4); // Assuming column 4 contains the total cost
        } else {
            model.addRow(new Object[]{"PO20", "CLOSEUP 100g", 1, priceOfItem, (priceOfItem + tax)});
        }
        itemCost();
    }//GEN-LAST:event_TOOTHPASTEActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed

    }//GEN-LAST:event_jTextField40ActionPerformed

    private void REMOVEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEBTNActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int RemoveItem = tbl.getSelectedRow();
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
        }
        itemCost();
    }//GEN-LAST:event_REMOVEBTNActionPerformed

    private void RESETBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETBTNActionPerformed
        cusId.setText("");
        cusName.setText("");
        subTotBox.setText("");
        taxBox.setText("");
        totalBox.setText("");
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_RESETBTNActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed

        String orderDate = orderDateBox.getText();
        String orderId = ORDIDBOX.getText();
        String customerId = cusId.getText();
        ArrayList<OrderDetail> orderDetailList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String itemCode = (String) dtm.getValueAt(i, 0);
            int orderqty = (int) dtm.getValueAt(i, 2);
            double unitPrice = (double) dtm.getValueAt(i, 3);
            OrderDetail orderDetail = new OrderDetail(orderId, itemCode, orderqty, unitPrice);
            System.out.println(orderDetail);
            orderDetailList.add(orderDetail);
        }

        Orders order = new Orders(orderId, orderDate, customerId, orderDetailList);

        try {
            boolean isAdded = OrderController.placeOrder(order);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            //JOptionPane.showMessageDialog(this, ex.getMessage());

        }


    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void ORDIDBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDIDBOXActionPerformed

    }//GEN-LAST:event_ORDIDBOXActionPerformed

    private void mainpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainpgActionPerformed
        main_frame hPge = new main_frame();
        hPge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainpgActionPerformed

    private void addCusFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusFormActionPerformed
        Quick_Access_Customer QAC = new Quick_Access_Customer();
        QAC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCusFormActionPerformed

    private void cmbItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemCodeActionPerformed
    public void itemCost() {
        double sum = 0;

        for (int i = 0; i < tbl.getRowCount(); i++) {
            double quantity = Double.parseDouble(tbl.getValueAt(i, 2).toString()); // Assuming column 3 contains the quantity
            double price = Double.parseDouble(tbl.getValueAt(i, 3).toString()); // Assuming column 4 contains the unit price
            sum += quantity * price;
        }

        double ctotal = sum;
        double cTax = (ctotal * 15) / 100;

        String iTaxTotal = String.format("Rs%.2f", cTax);
        taxBox.setText(iTaxTotal);

        String isubTotal = String.format("Rs%.2f", ctotal);
        subTotBox.setText(isubTotal);

        String iTotal = String.format("Rs%.2f", ctotal + cTax);
        totalBox.setText(iTotal);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thogaKade_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thogaKade_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thogaKade_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thogaKade_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new thogaKade_pos().setVisible(true);
        });
    }

    public void loadDate() {
        Date date = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        orderDateBox.setText(f.format(date));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANCHOR;
    private javax.swing.JButton ASTRA;
    private javax.swing.JButton BREAD;
    private javax.swing.JButton CHEESE;
    private javax.swing.JButton COCACOLA;
    private javax.swing.JButton DHAL;
    private javax.swing.JButton FACEWASH;
    private javax.swing.JButton FLOUR;
    private javax.swing.JButton OIL;
    private javax.swing.JTextField ORDIDBOX;
    private javax.swing.JButton PASTA;
    private javax.swing.JButton REMOVEBTN;
    private javax.swing.JButton RESETBTN;
    private javax.swing.JButton SAUCE;
    private javax.swing.JButton SUGAR;
    private javax.swing.JButton TOOTHPASTE;
    private javax.swing.JButton YOGHURT;
    private javax.swing.JButton addCusForm;
    private javax.swing.JButton cannedFish;
    private javax.swing.JButton chickPeas;
    private javax.swing.JComboBox cmbItemCode;
    private javax.swing.JTextField cusId;
    private javax.swing.JTextField cusName;
    private javax.swing.JButton greenGram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton keerisambaBtn;
    private javax.swing.JButton mainpg;
    private javax.swing.JTextField orderDateBox;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JButton redRawRice;
    private javax.swing.JTextField subTotBox;
    private javax.swing.JTextField taxBox;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField totalBox;
    private javax.swing.JButton whiteRice;
    // End of variables declaration//GEN-END:variables
}
