/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Item_table_jframes;

import Customer_table_Jframes.main_frame;
import controller.ItemController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Item;
public class Quick_Access_Item extends javax.swing.JFrame {

    /**
     * Creates new form sample_cus_form
     */
    public Quick_Access_Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodeBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUpricBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQOHBox = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", "UnitPrice", "qtyOnHand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(txtTbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 640, 400));

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 68)); // NOI18N
        jLabel5.setText("ITEMS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 230, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFramePackage/images/background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -80, -1, 810));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 720, 580));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtCodeBox.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        txtCodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeBoxActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, -1));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DESCRIPTION");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtDesBox.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        txtDesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesBoxActionPerformed(evt);
            }
        });
        jPanel3.add(txtDesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, -1));

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNITPRICE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtUpricBox.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        txtUpricBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpricBoxActionPerformed(evt);
            }
        });
        jPanel3.add(txtUpricBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QTYONHAND");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        txtQOHBox.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        txtQOHBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQOHBoxActionPerformed(evt);
            }
        });
        jPanel3.add(txtQOHBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, -1));

        addBtn.setBackground(new java.awt.Color(204, 51, 0));
        addBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel3.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, 60));

        updateBtn.setBackground(new java.awt.Color(204, 204, 0));
        updateBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel3.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 260, 60));

        searchBtn.setBackground(new java.awt.Color(102, 153, 0));
        searchBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 260, 60));

        deleteBtn.setBackground(new java.awt.Color(0, 153, 153));
        deleteBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 260, 60));

        viewBtn.setBackground(new java.awt.Color(153, 0, 153));
        viewBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 260, 60));

        cancelBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel3.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 200, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 590));

        setSize(new java.awt.Dimension(1079, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
          try {
            Item item = new Item(
                    txtCodeBox.getText(),
                    txtDesBox.getText(),
                    Double.parseDouble(txtUpricBox.getText()),
                    Integer.parseInt(txtQOHBox.getText())
            );

            boolean isUpdated = ItemController.updateItem(item);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Update Success...");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
           String code=txtCodeBox.getText();
        String dis=txtDesBox.getText();
        double uPrice=Double.parseDouble(txtUpricBox.getText());
        int COH = Integer.parseInt(txtQOHBox.getText());
        
        Item item=new Item(code,dis,uPrice,COH);
         try {
            boolean isAdded = ItemController.addItem(item);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
          
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        txtCodeBoxActionPerformed(evt);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            boolean isDeleted = ItemController.deleteItem(txtCodeBox.getText());
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Delete Success...");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        try {
            ArrayList<Item> itemList= ItemController.getAllCustomer();
            DefaultTableModel dtm=(DefaultTableModel) txtTbl.getModel();
            dtm.setRowCount(0);
            for(Item item:itemList){
                Object[]rowData={item.getCode(),item.getDescription(),item.getUnitPrice(),item.getQtyOnHand()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException  ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void txtCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeBoxActionPerformed
       try {
            Item item = ItemController.searchItem(txtCodeBox.getText());
            if (item != null) {
                txtDesBox.setText(item.getDescription());
                txtUpricBox.setText(item.getUnitPrice() + "");

                txtQOHBox.setText(String.valueOf(item.getQtyOnHand()));

            } else {
                JOptionPane.showMessageDialog(this, "Item not found..");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_txtCodeBoxActionPerformed

    private void txtDesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesBoxActionPerformed

    private void txtUpricBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpricBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpricBoxActionPerformed

    private void txtQOHBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQOHBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQOHBoxActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
      Item_main_page hPge = new Item_main_page();
        hPge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quick_Access_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quick_Access_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quick_Access_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quick_Access_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quick_Access_Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtCodeBox;
    private javax.swing.JTextField txtDesBox;
    private javax.swing.JTextField txtQOHBox;
    private javax.swing.JTable txtTbl;
    private javax.swing.JTextField txtUpricBox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
