
package Item_table_jframes;

import controller.ItemController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Item;

public class search_item_form extends javax.swing.JFrame {

    
    public search_item_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtId = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        txtSalary = new javax.swing.JLabel();
        txtCodeBox = new javax.swing.JTextField();
        txtDescrBox = new javax.swing.JTextField();
        txtUpriceBox = new javax.swing.JTextField();
        txtQOHBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 830, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Myanmar MN", 1, 42)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("SEARCH ITEM FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtId.setText("CODE");
        jPanel4.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtName.setText("DESCRIPTION");
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtAddress.setText("UNITPRICE");
        jPanel4.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        txtSalary.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtSalary.setText("QTYONHAND");
        jPanel4.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtCodeBox.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        txtCodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeBoxActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 240, 50));

        txtDescrBox.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        txtDescrBox.setEditable(false);
        txtDescrBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescrBoxActionPerformed(evt);
            }
        });
        jPanel4.add(txtDescrBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 240, 50));

        txtUpriceBox.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        txtUpriceBox.setEditable(false);
        txtUpriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpriceBoxActionPerformed(evt);
            }
        });
        jPanel4.add(txtUpriceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 50));

        txtQOHBox.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        txtQOHBox.setEditable(false);
        txtQOHBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQOHBoxActionPerformed(evt);
            }
        });
        jPanel4.add(txtQOHBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 240, 50));

        searchBtn.setBackground(new java.awt.Color(255, 153, 0));
        searchBtn.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel4.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 170, 50));

        cancelBtn.setBackground(new java.awt.Color(255, 153, 0));
        cancelBtn.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel4.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFramePackage/images/search Itemjpg.jpg"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, 200));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 830, 380));

        setSize(new java.awt.Dimension(828, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeBoxActionPerformed
       try {
            Item item = ItemController.searchItem(txtCodeBox.getText());
            if (item != null) {
                txtDescrBox.setText(item.getDescription());
                txtUpriceBox.setText(item.getUnitPrice()+"");
               // txtQOHBox.setText(item.getQtyOnHand());
               txtQOHBox.setText(String.valueOf(item.getQtyOnHand())); 

            } else {
                JOptionPane.showMessageDialog(this, "Item not found..");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_txtCodeBoxActionPerformed

    private void txtDescrBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescrBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescrBoxActionPerformed

    private void txtUpriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpriceBoxActionPerformed

    private void txtQOHBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQOHBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQOHBoxActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        txtCodeBoxActionPerformed(evt);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
         Item_main_page hPge = new Item_main_page();
        hPge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_item_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_item_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_item_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_item_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_item_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JTextField txtCodeBox;
    private javax.swing.JTextField txtDescrBox;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtName;
    private javax.swing.JTextField txtQOHBox;
    private javax.swing.JLabel txtSalary;
    private javax.swing.JTextField txtUpriceBox;
    // End of variables declaration//GEN-END:variables
}
